image:
  repository: test-harbor.lra-poc.com/library/node-app
  tag: latest

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: test-node-app.lra-poc.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - test-node-app.lra-poc.com
      secretName: node-app-tls  # Matches the cert-manager secret name

vault:
  enabled: true
  role: "node-app-role"
  secretPath: "secret/data/node-app"
  secretKeys:
    DB_USER: "DB_USER"
    DB_PASSWORD: "DB_PASSWORD"

serviceAccount:
  create: true
  name: "node-app-sa"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
